구조 다시잡기

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,94 +1,222 @@
-######################################
-##			IncludePost.mk			##
-######################################
-MAKE = make
-# c++ 컴파일러 지정
-CXX = g++ -std=c++11
-# 정적 라이브러리 생성을 유틸리티 지정
-AR = ar
-# 정적 라이브러리 목차 생성 라이브러리
-RANLIB = ranlib
-# 기타 명령어 선언
-RM = rm
-MKDIR = mkdir
- 
-# RELEASE, DEBUG 버전별 FLAG 지정
-# RELEASE 모드 컴파일시 'make RELEASE=1'로 컴파일
-ifeq ($(RELEASE), 1)
-OBJS_DIR  = $(PROJ_HOME)/Release
-DBG_FLAGS = -O2 -DNDEBUG
+#### PROJECT SETTINGS ####
+# The name of the executable to be created
+BIN_NAME := GameServer
+# Compiler used
+CXX ?= g++
+# Extension of source files used in the project
+SRC_EXT = cpp
+# Path to the source directory, relative to the makefile
+SRC_PATH = .
+# Space-separated pkg-config libraries used by this project
+LIBS = -Wl,-rpath="/usr/local/lib" -L/usr/local/lib -lboost_log -lpthread -lboost_thread -lboost_system
+# General compiler flags
+COMPILE_FLAGS = -std=c++11 -Wall -Wextra -g -DBOOST_LOG_DYN_LINK
+# Additional release-specific flags
+RCOMPILE_FLAGS = -D NDEBUG
+# Additional debug-specific flags
+DCOMPILE_FLAGS = -D DEBUG
+# Add additional include paths
+INCLUDES = -I $(SRC_PATH) -I/usr/local/include
+# General linker settings
+LINK_FLAGS =
+# Additional release-specific linker settings
+RLINK_FLAGS =
+# Additional debug-specific linker settings
+DLINK_FLAGS =
+# Destination directory, like a jail or mounted system
+DESTDIR = /
+# Install path (bin/ is appended automatically)
+INSTALL_PREFIX = usr/local
+#### END PROJECT SETTINGS ####
+
+# Generally should not need to edit below this line
+
+# Obtains the OS type, either 'Darwin' (OS X) or 'Linux'
+UNAME_S:=$(shell uname -s)
+
+# Function used to check variables. Use on the command line:
+# make print-VARNAME
+# Useful for debugging and adding features
+print-%: ; @echo $*=$($*)
+
+# Shell used in this makefile
+# bash is used for 'echo -en'
+SHELL = /bin/bash
+# Clear built-in rules
+.SUFFIXES:
+# Programs for installation
+INSTALL = install
+INSTALL_PROGRAM = $(INSTALL)
+INSTALL_DATA = $(INSTALL) -m 644
+
+# Append pkg-config specific libraries if need be
+ifneq ($(LIBS),)
+	#COMPILE_FLAGS += $(shell pkg-config --cflags $(LIBS))
+	COMPILE_FLAGS += $(LIBS)
+	#LINK_FLAGS += $(shell pkg-config --libs $(LIBS))
+	LINK_FLAGS += $(LIBS)
+endif
+
+# Verbose option, to output compile and link commands
+export V := false
+export CMD_PREFIX := @
+ifeq ($(V),true)
+	CMD_PREFIX :=
+endif
+
+# Combine compiler and linker flags
+release: export CXXFLAGS := $(CXXFLAGS) $(COMPILE_FLAGS) $(RCOMPILE_FLAGS)
+release: export LDFLAGS := $(LDFLAGS) $(LINK_FLAGS) $(RLINK_FLAGS)
+debug: export CXXFLAGS := $(CXXFLAGS) $(COMPILE_FLAGS) $(DCOMPILE_FLAGS)
+debug: export LDFLAGS := $(LDFLAGS) $(LINK_FLAGS) $(DLINK_FLAGS)
+
+# Build and output paths
+release: export BUILD_PATH := ../build/release
+release: export BIN_PATH := ../bin/release
+debug: export BUILD_PATH := ../build/debug
+debug: export BIN_PATH := ../bin/debug
+install: export BIN_PATH := ../bin/release
+
+# Find all source files in the source directory, sorted by most
+# recently modified
+ifeq ($(UNAME_S),Darwin)
+	SOURCES = $(shell find $(SRC_PATH) -name '*.$(SRC_EXT)' | sort -k 1nr | cut -f2-)
 else
-OBJS_DIR  = $(PROJ_HOME)/Debug
-DBG_FLAGS = -g -O0 -DDEBUG
+	SOURCES = $(shell find $(SRC_PATH) -name '*.$(SRC_EXT)' -printf '%T@\t%p\n' \
+						| sort -k 1nr | cut -f2-)
 endif
 
-# DEPEND 파일명 정의
-DEPEND_FILE = $(OBJS_DIR)/depend_file
-
-SRC_DIR = $(PROJ_HOME)/src
-
-# g++ 플래그 지정
-BOOSTFLAG = -DBOOST_LOG_DYN_LINK -I/usr/local/boost/include
-CPPFLAGS   = -g -W -Wall $(BOOSTFLAG)
-
-# Target 생성시 링크를 위한 Header 파일들 경로 지정
-SYS_INC  = 
-USER_INC = -I$(PROJ_HOME)/src/Log
-INCLUDE  = $(SYS_INC) $(USER_INC)
-
-# Target 생성시 링크를 위한 Library 파일 지정
-SYS_LIB  = -Wl,-rpath="/usr/local/boost/lib" -L/usr/local/boost/lib -lboost_log -lpthread -lboost_thread -lboost_system
-LIBS += -lLog
-USER_LIB = -L$(PROJ_HOME)/lib $(LIBS)
-ALL_LIB  = $(SYS_LIB) $(USER_LIB)
-
-# Target 생성정보 선언
-TARGET_SRCS = Test.cpp
-TARGET_OBJS = $(TARGET_SRCS:%.cpp=$(OBJS_DIR)/%.o)
-TARGET_NAMES = $(TARGET_SRCS:%.cpp=$(OBJS_DIR)/%)
-
-# make할 파일 확장자 지정 매크로
-.SUFFIXES : .cpp .o
-
-all : $(TARGET_NAMES)
-
-# 확장자 규칙으로 컴파일 옵션 지정
-$(OBJS_DIR)/%.o : %.cpp
-	@echo "=============================="
-	@echo "Compliling $@ "
-	@echo "=============================="
-	@test -d $(OBJS_DIR) || $(MKDIR) $(OBJS_DIR)
-	$(CXX) $(CPPFLAGS) $(DBG_FLAGS) $(INCLUDE) -c $< -o $@
-
-# Target 파일 생성 규칙 선언
-## 생성될 Target 파일이 여러개일경우 사용
-# .SECONDEXPENSION:
-## 각각의 Target에 해당하눈 .o파일 지정되게끔 지정
-# $(TARGET_NAMES) : $$@.o
-# 	$(CXX) -o $@ $< $(ALL_LIB) $(INCLUDE)
-
-## 생성될 Target 파일이 하나일경우 사용
-$(TARGET_NAMES) : $(TARGET_OBJS)
-	@echo "=============================="
-	@echo "Create Binary $@ "
-	@echo "=============================="
-	$(CXX) $< $(ALL_LIB) $(INCLUDE) -o $(TARGET_NAMES)
-
-depend :
-	@test -d $(OBJS_DIR) || $(MKDIR) $(OBJS_DIR)
-	@$(RM) -f $(DEPEND_FILE)
-	@for FILE in $(LIB_SRCS:%.cpp=%) $(TARGET_SRCS:%.cpp=%); do \
-		$(CXX) -MM -MT $(OBJS_DIR)/$$FILE.o $$FILE.cpp $(CPPFLAGS) $(DBG_FLAGS) $(INCLUDE) >> $(DEPEND_FILE); \
-	done
-
-clean :
-	$(RM) -rf $(TARGET_OBJS) $(TARGET_NAMES)
-
-# RELESE 버전 make시 의존성규칙 포함되지 않도록 선언
-ifneq ($(MAKECMDGOALS), clean)
-ifneq ($(MAKECMDGOALS), depend)
-ifneq ($(strip $(LIB_SRCS) $(TARGET_SRCS)),)
--include $(DEPEND_FILE)
+# fallback in case the above fails
+rwildcard = $(foreach d, $(wildcard $1*), $(call rwildcard,$d/,$2) \
+						$(filter $(subst *,%,$2), $d))
+ifeq ($(SOURCES),)
+	SOURCES := $(call rwildcard, $(SRC_PATH), *.$(SRC_EXT))
 endif
+
+# Set the object file names, with the source directory stripped
+# from the path, and the build path prepended in its place
+OBJECTS = $(SOURCES:$(SRC_PATH)/%.$(SRC_EXT)=$(BUILD_PATH)/%.o)
+# Set the dependency files that will be used to add header dependencies
+DEPS = $(OBJECTS:.o=.d)
+
+# Macros for timing compilation
+ifeq ($(UNAME_S),Darwin)
+	CUR_TIME = awk 'BEGIN{srand(); print srand()}'
+	TIME_FILE = $(dir $@).$(notdir $@)_time
+	START_TIME = $(CUR_TIME) > $(TIME_FILE)
+	END_TIME = read st < $(TIME_FILE) ; \
+		$(RM) $(TIME_FILE) ; \
+		st=$$((`$(CUR_TIME)` - $$st)) ; \
+		echo $$st
+else
+	TIME_FILE = $(dir $@).$(notdir $@)_time
+	START_TIME = date '+%s' > $(TIME_FILE)
+	END_TIME = read st < $(TIME_FILE) ; \
+		$(RM) $(TIME_FILE) ; \
+		st=$$((`date '+%s'` - $$st - 86400)) ; \
+		echo `date -u -d @$$st '+%H:%M:%S'`
 endif
+
+# Version macros
+# Comment/remove this section to remove versioning
+USE_VERSION := false
+# If this isn't a git repo or the repo has no tags, git describe will return non-zero
+ifeq ($(shell git describe > /dev/null 2>&1 ; echo $$?), 0)
+	USE_VERSION := true
+	VERSION := $(shell git describe --tags --long --dirty --always | \
+		sed 's/v\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)-\?.*-\([0-9]*\)-\(.*\)/\1 \2 \3 \4 \5/g')
+	VERSION_MAJOR := $(word 1, $(VERSION))
+	VERSION_MINOR := $(word 2, $(VERSION))
+	VERSION_PATCH := $(word 3, $(VERSION))
+	VERSION_REVISION := $(word 4, $(VERSION))
+	VERSION_HASH := $(word 5, $(VERSION))
+	VERSION_STRING := \
+		"$(VERSION_MAJOR).$(VERSION_MINOR).$(VERSION_PATCH).$(VERSION_REVISION)-$(VERSION_HASH)"
+	override CXXFLAGS := $(CXXFLAGS) \
+		-D VERSION_MAJOR=$(VERSION_MAJOR) \
+		-D VERSION_MINOR=$(VERSION_MINOR) \
+		-D VERSION_PATCH=$(VERSION_PATCH) \
+		-D VERSION_REVISION=$(VERSION_REVISION) \
+		-D VERSION_HASH=\"$(VERSION_HASH)\"
 endif
+
+# Standard, non-optimized release build
+.PHONY: release
+release: dirs
+ifeq ($(USE_VERSION), true)
+	@echo "Beginning release build v$(VERSION_STRING)"
+else
+	@echo "Beginning release build"
+endif
+	@$(START_TIME)
+	@$(MAKE) all --no-print-directory
+	@echo -n "Total build time: "
+	@$(END_TIME)
+
+# Debug build for gdb debugging
+.PHONY: debug
+debug: dirs
+ifeq ($(USE_VERSION), true)
+	@echo "Beginning debug build v$(VERSION_STRING)"
+else
+	@echo "Beginning debug build"
+endif
+	@$(START_TIME)
+	@$(MAKE) all --no-print-directory
+	@echo -n "Total build time: "
+	@$(END_TIME)
+
+# Create the directories used in the build
+.PHONY: dirs
+dirs:
+	@echo "Creating directories"
+	@mkdir -p $(dir $(OBJECTS))
+	@mkdir -p $(BIN_PATH)
+
+# Installs to the set path
+.PHONY: install
+install:
+	@echo "Installing to $(DESTDIR)$(INSTALL_PREFIX)/bin"
+	@$(INSTALL_PROGRAM) $(BIN_PATH)/$(BIN_NAME) $(DESTDIR)$(INSTALL_PREFIX)/bin
+
+# Uninstalls the program
+.PHONY: uninstall
+uninstall:
+	@echo "Removing $(DESTDIR)$(INSTALL_PREFIX)/bin/$(BIN_NAME)"
+	@$(RM) $(DESTDIR)$(INSTALL_PREFIX)/bin/$(BIN_NAME)
+
+# Removes all build files
+.PHONY: clean
+clean:
+	@echo "Deleting $(BIN_NAME) symlink"
+	@$(RM) $(BIN_NAME)
+	@echo "Deleting directories"
+	@$(RM) -r ../build
+	@$(RM) -r ../bin
+
+# Main rule, checks the executable and symlinks to the output
+all: $(BIN_PATH)/$(BIN_NAME)
+	@echo "Making symlink: $(BIN_NAME) -> $<"
+	@$(RM) $(BIN_NAME)
+	@ln -s $(BIN_PATH)/$(BIN_NAME) $(BIN_NAME)
+
+# Link the executable
+$(BIN_PATH)/$(BIN_NAME): $(OBJECTS)
+	@echo "Linking: $@"
+	@$(START_TIME)
+	$(CMD_PREFIX)$(CXX) $(OBJECTS) $(LDFLAGS) -o $@
+	@echo -en "\t Link time: "
+	@$(END_TIME)
+
+# Add dependency files, if they exist
+-include $(DEPS)
+
+# Source file rules
+# After the first compilation they will be joined with the rules from the
+# dependency files to provide header dependencies
+$(BUILD_PATH)/%.o: $(SRC_PATH)/%.$(SRC_EXT)
+	@echo "Compiling: $< -> $@"
+	@$(START_TIME)
+	$(CMD_PREFIX)$(CXX) $(CXXFLAGS) $(INCLUDES) -MP -MMD -c $< -o $@
+	@echo -en "\t Compile time: "
+	@$(END_TIME)
